-- Create the payment_settings table
create table public.payment_settings (
  id bigint generated by default as identity primary key,
  provider text not null default 'intasend',
  public_key text not null,
  is_live boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert a default row (Updated for Flutterwave)
insert into public.payment_settings (id, provider, public_key, is_live)
values (1, 'flutterwave', 'FLWPUBK_TEST-SANDBOXDEMO-X', false);

-- Enable Row Level Security (RLS)
alter table public.payment_settings enable row level security;

-- Create policies (Adjust these based on your auth setup)
-- Allow read access to everyone (so the frontend can load the public key)
create policy "Enable read access for all users" on public.payment_settings
  for select using (true);

-- Allow insert/update only for authenticated users (admins)
-- If you don't have auth set up yet, you can use 'true' for testing, but be careful!
create policy "Enable insert for authenticated users only" on public.payment_settings
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on public.payment_settings
  for update using (auth.role() = 'authenticated');
