-- Enable Row Level Security (RLS) recommended for production, but can be disabled for testing
-- For this initial setup, we will create tables. You can run this in the Supabase SQL Editor.

-- 1. Create Routes Table
create table public.trinity_routes (
  id bigint generated by default as identity primary key,
  origin text not null,
  country_origin text,
  destination text not null,
  country_dest text,
  price text not null,
  vip_price text,
  duration text,
  country text,
  image text,
  rating numeric,
  next_bus text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Bookings Table
create table public.trinity_bookings (
  id uuid default gen_random_uuid() primary key,
  route_id bigint references public.trinity_routes(id),
  origin text,
  destination text,
  date date,
  time text,
  seat integer,
  passengers integer,
  passenger_name text,
  phone_number text,
  total_price text,
  payment_method text,
  status text default 'pending',
  device_type text,
  user_location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Contact Info Table
create table public.trinity_contact_info (
  id integer primary key generated by default as identity,
  phone_ke text,
  phone_ug text,
  phone_rw text,
  whatsapp text,
  email text,
  address_ke text,
  address_ug text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Create Payment Methods Table
create table public.trinity_payment_methods (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  type text,
  account_number text,
  account_name text,
  instructions text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Payment Settings (API Keys)
create table public.trinity_payment_settings (
  id integer primary key generated by default as identity,
  provider text not null default 'intasend',
  public_key text,
  secret_key text,
  is_live boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Seed Initial Data (Optional - based on your current hardcoded data)

-- Routes
INSERT INTO public.trinity_routes (origin, country_origin, destination, country_dest, price, duration, country, image, rating, next_bus)
VALUES
('Nairobi', 'Kenya', 'Kampala', 'Uganda', 'KSh 3,500', '12 hours', 'Uganda', 'https://coreva-normal.trae.ai/api/ide/v1/text_to_image?prompt=Nairobi%20city%20skyline%20modern%20buildings%20sunny%20day&image_size=landscape_4_3', 4.8, '08:00 AM'),
('Nairobi', 'Kenya', 'Kigali', 'Rwanda', 'KSh 7,000', '15 hours', 'Rwanda', 'https://coreva-normal.trae.ai/api/ide/v1/text_to_image?prompt=Kigali%20convention%20center%20rwanda%20night%20lights&image_size=landscape_4_3', 4.9, '07:30 AM'),
('Nairobi', 'Kenya', 'Goma', 'DR Congo', 'KSh 8,000', '19 hours', 'DR Congo', 'https://coreva-normal.trae.ai/api/ide/v1/text_to_image?prompt=Goma%20congo%20city%20view%20volcano%20background%20scenic&image_size=landscape_4_3', 4.6, '05:00 AM'),
('Nairobi', 'Kenya', 'Juba', 'South Sudan', 'KSh 8,500', '14 hours', 'South Sudan', 'https://coreva-normal.trae.ai/api/ide/v1/text_to_image?prompt=Juba%20bridge%20south%20sudan%20river%20nile&image_size=landscape_4_3', 4.7, '06:00 AM'),
('Nairobi', 'Kenya', 'Bujumbura', 'Burundi', 'KSh 7,500', '16 hours', 'Burundi', null, null, null),
('Nairobi', 'Kenya', 'Mbarara', 'Uganda', 'KSh 6,500', '13 hours', 'Uganda', null, null, null),
('Nairobi', 'Kenya', 'Kabale', 'Uganda', 'KSh 5,000', '14 hours', 'Uganda', null, null, null),
('Nairobi', 'Kenya', 'Bukavu', 'DR Congo', 'KSh 7,500', '20 hours', 'DR Congo', null, null, null),
('Kampala', 'Uganda', 'Nairobi', 'Kenya', 'UGX 100,000', '12 hours', 'Kenya', null, null, null),
('Kampala', 'Uganda', 'Kigali', 'Rwanda', 'UGX 80,000', '9 hours', 'Rwanda', null, null, null),
('Kampala', 'Uganda', 'Juba', 'South Sudan', 'UGX 120,000', '10 hours', 'South Sudan', null, null, null),
('Kigali', 'Rwanda', 'Nairobi', 'Kenya', 'RWF 70,000', '15 hours', 'Kenya', null, null, null),
('Kigali', 'Rwanda', 'Kampala', 'Uganda', 'RWF 35,000', '9 hours', 'Uganda', null, null, null),
('Nairobi', 'Kenya', 'Dar es Salaam', 'Tanzania', 'KSh 4,500', '14 hours', 'Tanzania', null, null, null),
('Mombasa', 'Kenya', 'Nairobi', 'Kenya', 'KSh 2,500', '8 hours', 'Kenya', null, null, null);

-- Contact Info
INSERT INTO public.trinity_contact_info (phone_ke, phone_ug, phone_rw, whatsapp, email, address_ke, address_ug)
VALUES ('+254 751 494564', '+256 747 180552', '+250 735 589845', '+254 755 356 109', 'Trinityexpressbus@gmail.com', 'Duruma Road, Nairobi, Kenya', 'Namirembe Road, Bakuli, Kampala');

-- Payment Methods
INSERT INTO public.trinity_payment_methods (name, type, account_number, account_name, instructions)
VALUES ('M-Pesa', 'paybill', '400200', 'Trinity Express', 'Enter your booking reference as account number');

-- Payment Settings
INSERT INTO public.trinity_payment_settings (provider, public_key, is_live)
VALUES ('intasend', 'ISPubKey_test_800c1e69-0292-426c-a811-58079737154d', false);

-- Enable RLS (Security) - Optional for now but recommended
alter table public.trinity_routes enable row level security;
alter table public.trinity_bookings enable row level security;
alter table public.trinity_contact_info enable row level security;
alter table public.trinity_payment_methods enable row level security;
alter table public.trinity_payment_settings enable row level security;

-- Create policies (Allow Public Read, Allow Anon/Auth Insert/Update for now for simplicity of the migration)
-- In production, you'd want stricter policies.
create policy "Public routes are viewable by everyone" on public.trinity_routes for select using (true);
create policy "Enable all access for routes" on public.trinity_routes for all using (true);

create policy "Public contact info is viewable by everyone" on public.trinity_contact_info for select using (true);
create policy "Enable all access for contact info" on public.trinity_contact_info for all using (true);

create policy "Public payment methods are viewable by everyone" on public.trinity_payment_methods for select using (true);
create policy "Enable all access for payment methods" on public.trinity_payment_methods for all using (true);

create policy "Public payment settings viewable by everyone" on public.trinity_payment_settings for select using (true);
create policy "Enable all access for payment settings" on public.trinity_payment_settings for all using (true);

-- Allow anyone to create a booking (since we don't have auth for users yet)
create policy "Anyone can create bookings" on public.trinity_bookings for insert with check (true);
create policy "Bookings viewable by everyone" on public.trinity_bookings for select using (true);
create policy "Enable all access for bookings" on public.trinity_bookings for all using (true);
